### ISSUE TITLE
"Add to now playing" pauses the music on Linux

### ISSUE THREAD

**Issue by Darkempire78** [harmonoid/harmonoid#121]
**Describe the bug**
To click on "Add to now playing" pauses the current music on Linux (but add the music to the queue)

**To Reproduce**
1. Go to 'YouTube
2. Click on a music
3. Click on "Add to now playing"

**Expected behavior**
Do not pause the current music

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave
 - Version 0.1.8 (Harmonoid)

**Comment by alexmercerind** [comment]
@Darkempire78 hope you're doing great! We have massively revamped the app's UI & improved YouTube performance to be same as the webapp. Still working on other things though. However, your issue is now fixed.

Can't seem to reproduce now.

Download: https://github.com/harmonoid/harmonoid/releases/tag/v0.2.0

<table>
<tr>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/0.jpeg?raw=true'></img>
</td>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/4.jpeg?raw=true'></img>
</td>
</tr>
</table>
