### ISSUE TITLE
Can you add Zune/windows phone like feeling of UI but keep it modern yet still amazing!

### ISSUE THREAD

**Issue by fisforfaheem** [harmonoid/harmonoid#149]
millions of us love windows phone design and want to see if you could do that! :)

**Comment by webprofusion-chrisc** [comment]
The UI is already nice, what *exactly* needs to change?

**Comment by webprofusion-chrisc** [comment]
And this should be a discussion, not an Issue.

**Comment by fisforfaheem** [comment]
Well, there wasn't an option for discussion so i had to write here, no
offense, But all I say is that the DEV behind the interface sees and
experiences windows phone 8.1 and windows phone 10
just to see the Ui and UX... If possible...maybe using an emulator or an
old phone..

Just a suggestion, But please do consider, Nice day

**Comment by alexmercerind** [comment]
Closing this. In future, we will (if I stay with same motivation as I'm in right now) add a theme system allowing to switch between Fluent (all mica etc. in its glory), Material (ripple effects & shadows etc) & other design systems.

I already wasted plenty of time in one of the earlier releases trying to "redesign" things where design is just a opinion based thing and current Material design looks definitely sleek & beautiful to me. There are already many apps (from Microsoft themselves) which use standard windows controls instead of this design.

Rolling out new Windows release today 🎉. You may [download](https://github.com/harmonoid/harmonoid/releases/tag/v0.1.9) & share your feedback with us at Discord.
