### ISSUE TITLE
Add UPI options for donation 

### ISSUE THREAD

**Issue by soumyabratabose** [harmonoid/harmonoid#187]
**Describe the new feature you'd like**

Add UPI options for donations alongside PayPal 

Thanks, for the app. I want to support your work, but I don't have PayPal.

**Comment by alexmercerind** [comment]
Thanks for considering this for me.

A big update has just been released: [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

A ton of features like following have been added since:
- Volume boost.
- Pitch shifting.
- Speed change.
- Synced lyrics.
- .LRC file support.
- Better & performant music library management.

While still following the same consistent Material Design.

**Comment by alexmercerind** [comment]
My UPI is at `saini123hitesh@oksbi` if you really consider it.
