### ISSUE TITLE
Link accounts

### ISSUE THREAD

**Issue by ItzSwirlz** [harmonoid/harmonoid#228]
This might be hard (thanks Google..), but be able to link accounts cross-platform. I did this when transitioning from Spotify to YT Music.

I don't know what its like to create your own Google 'application' like SongShift or Soundiiz, nor if Dart even has *ANY* support for it but I'll see.

P.S. As a first time contributor,I'm going to try to see if I can work with my spanish teacher to create some translations

Similar to #189 but it can also when searching for songs pull information from YT Music, like a webapp, i guess

**Comment by alexmercerind** [comment]
Thanks for the feedback!

We recently "completed"/"stabilized" our local music playback.
Now we have time to play with other interesting features & most importantly improving YouTube Music support (or adding other music services with time).

All this stuff is really "ahead of time", since Flutter & Dart etc. in general are very new in field of desktop development. Still, I feel what's already been done looks great & we're set to improve with time.

**Comment by DovePod** [comment]
[Exportify](https://github.com/watsonbox/exportify) looks like a good place to export your info. Idk if this is any help to you but ¯\_(ツ)_/¯.

**Comment by alexmercerind** [comment]
> [Exportify](https://github.com/watsonbox/exportify) looks like a good place to export your info. Idk if this is any help to you but ¯_(ツ)_/¯.

Thanks for joining the conversation. I think it's good. 
However, we will be able to add our own authentication for Spotify. But, YouTube Music on the other hand, linking is very tough.

**Comment by mytja** [comment]
On it.

Duplicates of this issue are:
- https://github.com/harmonoid/harmonoid/issues/143
- https://github.com/harmonoid/harmonoid/issues/189

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
