### ISSUE TITLE
Please remember increasing versionCode

### ISSUE THREAD

**Issue by IzzySoft** [harmonoid/harmonoid#268]
The last releases have identical versionCodes (5003). As Android uses `versionCode` to tell versions apart: can you please take care to increase it always before releasing? Guess it only slipped through this time, but it wasn't updated with the previous release either as you [can see here](https://github.com/harmonoid/harmonoid/blob/v0.2.2/pubspec.yaml#L7) at v0.2.2 and [here](https://github.com/harmonoid/harmonoid/blob/v0.2.0/pubspec.yaml#L4) at v0.2.0 :scream:

Thanks for taking care! And of course thanks for providing your app as open-source under a free license :+1:

**Comment by alexmercerind** [comment]
Windows & Linux are primarily targeted platforms currently (completely different dependencies, implementation & UI).
Currently I'm not targeting Android as a primary form of distribution. Android version is _just something that exists, but I'm not much proud of_. 

The application has been written from ground up (and no longer has same UI, functionality, dependencies, licensing or source code) & older versions are no longer available on the repository. Those older versions worked, but never in a way I'd want anyone to use at this point. 
At this point, the app is perfectly usable & has all basic functionalities implemented the way they should be (while more features are being worked on).

`v0.2.0` didn't even have an Android version in it. I have currently "hidden" the Google Play version of the application & will release it there again once I have the confidence & I haven't incremented the version code for the same reason.

I don't want redistribution of application (from any platform where I don't have any control over updating app details like feature-list, screenshots, other details / and isn't endorsed by me).

As for the licensing change, I've switched away from GPL-3.0 for now because:
1. Project depends on some [new internal dependencies](https://github.com/harmonoid/harmonoid/tree/master/external) which are NOT PUBLIC YET (and only available to patreons, along with other currently w.i.p. stuff), to leverage a large number of functionalities (because no other equivalent community open-source libraries are present). 
2. I don't want third-party sites to reproduce the application without prior permission, it takes away the "guarantee of it working as intended".

Same updates have been provided in project's README & version changelogs.

**Comment by IzzySoft** [comment]
Thanks for the detailed answer! As your app is currently [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.alexmercerind.harmonoid), shall I then remove it – or just leave it "stuck" at v0.2.4 marking it accordingly (i.e. that it's no longer FOSS and thus will have no more updates in my repo)? I've just prepared the latter variant (will go into effect with the next sync).

**Comment by alexmercerind** [comment]
> Thanks for the detailed answer! As your app is currently [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.alexmercerind.harmonoid), shall I then remove it – or just leave it "stuck" at v0.2.4 marking it accordingly (i.e. that it's no longer FOSS and thus will have no more updates in my repo)? I've just prepared the latter variant (will go into effect with the next sync).

Hey @IzzySoft! Sorry for taking your time, but I'd like to have the project unlisted/removed from your repository. 
Android version has been ignored for a really long time & the old version (which is present there) is genuinely unusable and I don't see myself working on open source anymore.

Thanks!

**Comment by IzzySoft** [comment]
Done (effective with the next sync at 6 pm UTC). Should things change, just give me a ping for re-listing if you want it back. Until then, all the best!
