### ISSUE TITLE
App crashes in a non-mounted disk (Linux)

### ISSUE THREAD

**Issue by Bryceed** [harmonoid/harmonoid#274]
**Describe the bug**
Critical error on open the app - when the installed disk are not mounted in the session (not clicked in the explorer to be loaded), so the app create this error but not specify how to solve it.

**To Reproduce**
There's nothing to do, it's the only screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/42657376/168685187-b99742ad-a88b-4ab3-b17f-7b2ae979f6aa.png)

**Desktop**
 - OS: Linux Mint (Ubuntu based)
 - Version: 20.3 Cinnamon

**Comment by Bryceed** [comment]
The solution it's not related to denied permissions (pt-br: "Permissão negada"), but to mounting the disk itself, after that the app work as expected.

**Comment by alexmercerind** [comment]
Hi! I also think mounting disk is important but I don't know any relevant Linux command/API for the same (mounting the specified disk, which was there earlier). Please feel free to share if you have some knowledge regarding this.

Thanks.

**Comment by Bryceed** [comment]
**Hi!**

I also don't know, in Flutter, a native way to call the disk mounting throught the system API, but I think a treated error screen with a basic list of the possible problem (_can be the unmounted disk, wrong permissions, locked disk [a.k.a "SD card reader lock"], encrypted disk, etc_) for a standard Linux user, can be a realistic approach despite the _supposed_ limitation of the app's technology.

If I find a code solution, I'll return to PR this. 
**Thanks!**

**Comment by ecollart** [comment]
Yes, it gives a warning but do not allow to correct the problem by going in parameters if that unmounted disk is the only one defined..
![Capture d’écran du 2022-08-19 16-49-53](https://user-images.githubusercontent.com/25539033/185646856-640d3484-cbd8-42a0-b32c-56a160cf6ceb.png)

Eric Collart

**Comment by alexmercerind** [comment]
@ecollart 

> Yes, it gives a warning but do not allow to correct the problem by going in parameters if that unmounted disk is the only one defined.

Maybe you can setup a shortcut such that it mounts the required disk / logical-volume to the required path (I'm pretty sure there's a command for that too) & then launches Harmonoid using `harmonoid` command.

OR just store your music somewhere in `/home/`.

<hr>

I have kept this issue open since I don't have any opinion on this.

For now, you should mount the disk manually & then continue in the application.
If you are aware of some Linux API that allows to take care of this or want any other behavioural change which is expected, then let me know.

As far as I know, same disk / logical-volume may be mounted to some different mount path. e.g.
-  If some other disk is already mounted on the same path.
-  Some file explorers assign random mount path everytime.

Another problem is how do I know that a mount path belongs to that particular disk specifically. So, I don't know what should I do to handle it within the application.

**Comment by ecollart** [comment]
Hello,
I am not asking Harmonoid corrects the problem for me, it would be great if it let me go to parameters to adapt my library location.
For now, the "Remove" option doesn't work because there is only 1 disk defined. So adding a button to go to parameters would be great !
This disk is normally defined in FStab but it seems the GUID changed for whatever reason so Harmonoid continues to complain it is not there ...
I am not a specialist so it's just hypothesis...
If you let me know how to remove completely Harmonoid, I can also re-install it from scratch and defined the good pah again to see how it goes...
Thanks any for the reactivity here. I was about to publish a test of Harmonoid on my blog (https://ecollart.xyz, in French but translatable using Google translate) when I faced this problem...
Eric Collart

**Comment by alexmercerind** [comment]
> Hello, I am not asking Harmonoid corrects the problem for me, it would be great if it let me go to parameters to adapt my library location. For now, the "Remove" option doesn't work because there is only 1 disk defined. So adding a button to go to parameters would be great ! This disk is normally defined in FStab but it seems the GUID changed for whatever reason so Harmonoid continues to complain it is not there ... I am not a specialist so it's just hypothesis... If you let me know how to remove completely Harmonoid, I can also re-install it from scratch and defined the good pah again to see how it goes... Thanks anyway for the reactivity here. I was about to publish a test of Harmonoid on my blog (https://ecollart.xyz, in French but translatable using Google translate) when I faced this problem... Eric Collart

Hey! Thanks for bringing this into my consideration. I'll add an option to open `Settings` from that dialog.
Currently. I'm working on a major next update, so a lot of things are to change & many new features will be there around in a week. I'll be really glad if you wait a little!

For now, you may delete `.Harmonoid` from your home folder to clear cache of the application.

**Comment by ecollart** [comment]
Hello,
absolutely no problem to wait next update of your already great job !
Thanks again for so quick support !
Eric Collart

**Comment by alexmercerind** [comment]
@ecollart,

The promised new update has now been released: [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

And there's a lot that's been added to existing.
