### ISSUE TITLE
[bug] linux: very (too) long indexing

### ISSUE THREAD

**Issue by manu-p** [harmonoid/harmonoid#316]
**Describe the bug**
+12000 tracks indexing takes hours

**To Reproduce**
1. Add a new folder containing more than 10000 tracks located on an external USB disk, the user account being on a SSD.
2. See what's happening: indexing is fast for few hundred of 1st tracks and then is very slow: more than 1 second for each track.

**Expected behavior**
A much faster indexing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Version : 0.2.8

Rhythmbox, for instance, had been indexing the same folder very much faster.

See [here](https://mega.nz/file/ZSwEWaoC#PNAiQepLbf6bi6vDLgdfa84kHhmTa5gYTmDEaw5ntuE).

**Comment by alexmercerind** [comment]
Attach videos for reference.

**Comment by manu-p** [comment]
See [here](https://mega.nz/file/ZSwEWaoC#PNAiQepLbf6bi6vDLgdfa84kHhmTa5gYTmDEaw5ntuE).

**Comment by alexmercerind** [comment]
> See what's happening: indexing is fast for few hundred of 1st tracks and then is very slow: more than 1 second for each track.

@manu-p,

Wait. I think I know it's cause. Current Linux binaries leak memory & I have no control over it since Flutter is very new in-terms of desktop application development.


**However,**

A fix (more like "circumvention") is planned for next release for Linux (out in few days). Could you please share your feedback with latest nightly: https://github.com/harmonoid/nightly/releases/tag/nightly

It'd be a really great feedback for the changes made.

Thanks for the video!

**Comment by alexmercerind** [comment]
Just to prove serious-ness,

_I'm eagerly waiting for your feedback on v0.2.9 nightly._

Indexing speeds are really fast compared to other music players, it's just that things clogged at the end due to memory leak This DOESN'T HAPPEN ON Windows for some reason, even though exact same code is being compiled.
This has been patched in that release though.

**Comment by manu-p** [comment]
Thanks, I confirm it's very very much faster with the nightly build (needed to remove ~/.Harmony folder). See [here](https://mega.nz/file/RagEWagD#Qn10PZ6k30MiXhgrUbNaUxJs48gBR-L0bhMszbXStk8).

**Comment by manu-p** [comment]
You also can see the log track since, this time, I started harmonoid in a terminal.

**Comment by alexmercerind** [comment]
> You also can see the log track since, this time, I started harmonoid in a terminal.

Sorry for the message yet again. The log unfortunately doesn't seem very promising :sweat_smile:.

- Are their any corrupt files in your folder?
- Is the music library inside Harmonoid actually populating (see by going back from the `Settings` page)?

**Comment by manu-p** [comment]
Harmonoid looks like running fine, despite all these messages permanently displayed in the terminal...

And so far I like it! Thanks!!!

Now the question is: how can I import my rhythmbox playlists? But I guess it's another story.

**Comment by alexmercerind** [comment]
Hi @manu-p,

[v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9) has been released. This bug was fixed in nightly releases.

I hope you found a better alternative to Rythmbox.
