### ISSUE TITLE
[Feature Request]: Android UI Suggestions

### ISSUE THREAD

**Issue by NaiveInvestigator** [harmonoid/harmonoid#326]
I was thinking that instead of having separate buttons for shuffle and loops, why not have just only one button and it will cycle through shuffle, loop playlist, loop song only, etc. And from the freed space we could use instead put the add to playlist button. We do have a like button which adds it to the favorites playlist but i think it will be handy for ppl who have multiple playlists.

I am still thinking how to make lyrics see more intuitively but the current arrangement is also good tho. Maybe swiping down ig? Or we can make it appear just below the song name just like the image below.

![image](https://user-images.githubusercontent.com/72654596/188461954-ea6e6609-fb48-44ee-a231-abf6f29a8525.png)

And could we also add a sleep timer? It will pause playback after a certain amount of time has passed as user has set, similar to Spotify. Very handy for ppl who listen to music and go to sleep.

 Feel free to disregard ones that you feel are against your vision. I hope this helps.

**Comment by alexmercerind** [comment]
Hi!


## Introduction

First of all, [a new Android version has been released](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.1). A lot of performance issues & jitter in UI has been fixed. Major work has went into migrating to modern Android storage 

## Example

This is something which looks _fine_ in pictures, but targeting different screen sizes has it's own challenges.

Take this 1280x768 Android 5.0 Nexus 4, which we support:

<img src="https://user-images.githubusercontent.com/28951144/190951027-f337b667-1719-4626-a6f8-8bc069b835a1.png" width="300"></img>

On the other hand, the UI is adapted to also look good on modern taller devices:

Additional space for playlist slide panel & volume slider could be justified.

<img src="https://user-images.githubusercontent.com/28951144/190951448-8b5efd5c-5af2-4466-aa8c-e977feed597f.png" width="300"></img>


## Personal opinion

I personally like current Material Design very-much, I don't want to change it much.
I will make any hard decisions soon because Harmonoid will migrate to [Material Design 3](https://m3.material.io) in future updates, BUT, it will still keep current design [Material Design 2](https://material.io/) optional in settings.
It'll need many tweaks & changes like deciding how it feels on Windows, Linux & Android or picking system wallpaper color etc., where somewhere along the line, I can address other things like this.
I target all 3 platforms, a lot of work.

## Adding few videos

Credits to Google & the Material Design team.

- [Material Design](https://user-images.githubusercontent.com/28951144/190951843-95cfc61f-a2e9-4a70-a9fd-d0638552446f.webm)
- [Material Design 2](https://user-images.githubusercontent.com/28951144/190951801-c2f5e5a8-860e-4471-8c7d-a70237cb5844.webm)
- [Material Design 3](https://video.twimg.com/ext_tw_video/1564666717594599424/pu/vid/1920x1080/VE7llGoBHF-R7OwI.mp4?tag=14)

## Future development

If you see the last video, the latest Material Design 3 spec, you'll see there are some widget designs are shown.
So, implementing Material Design 3 should be before #325, so that widgets follow latest scheme.

This is just the design alone, apart from this I have actual features to implement, existing performance issues to fix & other code to refactor. However, I'm really happy with what's been done & using it daily now, so I'm not that hurried.

Now, Harmonoid is nearly perfect & usable as-is, design updates come & go.

Direction of development is driven by the project's Patreons. I will implement Material Design 3 in public version likely, but my first focus is to focus on a exclusive "Pro" version for Patreons with more features.

It doesn't mean that I will remove features from free public version or it's incomplete, it's good & usable. There are no annoying labels with "buy" or ads. Most features are already there now. It's just going to be even better & a way to say thanks to the supporters.
