### ISSUE TITLE
[Feature request] Publish/release on F-Droid

### ISSUE THREAD

**Issue by Zastando** [harmonoid/harmonoid#332]
Are there any plans on publishing/releasing Harmonoid on F-Droid ?
It would be great, since F-Droid stands for free and open-source.

**Comment by alexmercerind** [comment]
Hi @Zastando,
Harmonoid doesn't actually fall in the category of libre / FOSS. A number of internal packages & code is not public yet.

Few of the sub-projects that I made & Harmonoid depends upon are:
- [media_engine](https://github.com/harmonoid/media_engine) : Media playback & tagging engine that powers Harmonoid. Based on libmpv. Complete with pitch shifting, volume boost, speed change, playlist management, performant tag-reader & more. Powers Harmonoid on Windows & Linux.
- [media_library](https://github.com/harmonoid/media_library) : A powerful media library indexer. Indexes & updates media from multiple selected directories into artists, albums, tracks & genres based on metadata tags. Complete with sorting, deletion, ordering & playlists support.
- [smtc-win32](https://github.com/harmonoid/smtc-win32) : System Media Transport Controls for Dart & Flutter. Gives Harmonoid native OS media controls on Windows.
- [mpris_service.dart](https://github.com/mpris_service.dart) : A Dart library to integrate Media Player Remote Interfacing Specification (MPRIS). Gives Harmonoid native OS media controls on Linux.

These are only available for Patreons. Harmonoid is distributed under [EULA](https://github.com/harmonoid/harmonoid/blob/master/EULA.txt).
I write/wrote every single line of code present in Harmonoid, for every platform Windows, Linux or Android.
By this, I'm able to ensure good quality of every release.

I have no fear in sharing my code because they have no sketchy things in them, but only with those who value it.
If I make my work 100% free just now, there will be 10 different forks with different names & minor changes claiming their name on my hard-work.

> It would be great, since F-Droid stands for free and open-source.

Everyone stands for free & open-source, but no-one stands for free & open-source developers. I've given up on open-source.
