### ISSUE TITLE
[Android] Shuflle button does not play songs randomly

### ISSUE THREAD

**Issue by FloRyuK0** [harmonoid/harmonoid#333]
Hello everyone, I don't know if this is because of the metadata of my songs but it does not play random anymore
it was before, but I think before version 0.3.0, so i updated to 0.3.2 but it's the same

i do not have this bug in the windows version with the exactly same files 

**To Reproduce**

1. Open the app
2. Go to tracks
3. Start a song
4. Press the shuffle button 

**Expected behavior**

the songs play randomly

**Screenshots**

see the screenshot with the red circle
![screenshot](https://user-images.githubusercontent.com/114009421/191304788-c25b91e0-3133-432e-b447-a407c63350d0.jpg)
as you can see, the songs goes to alphabetic order 

**Platform (please complete the following information)**

- OS: Android
- Version 11

**App version**
- Version: [e.g. v0.3.2]

**Comment by alexmercerind** [comment]
Hi @FloRyuK0,
Thanks for the report!
First off, shuffle works differently on Harmonoid Windows/Linux & Harmonoid Android.

**On Windows/Linux:**

Shuffle causes the current playlist to get randomized & player follows the newly generated random sequence.

**On Android:**

Shuffle does not randomize the playlist, but when song changes (upon song completion), app picks a random song & jumps to it instead of the next one.

Both cause shuffle to take place.

Android builds before v0.3.0 _were rolled out without much intention_.
I have worked heavily on new Android versions & a lot of improvement can be seen in features (like grid size, pitch shift, speed change, lyrics view, LRC support, audio output info & a lot more), performance, & stability.

<hr>

I hope I understood it correctly.

**Comment by alexmercerind** [comment]
Hi @FloRyuK0, the bug has been fixed.

I've updated the same link with updated APK (with fix): [Download](https://harmonoid.com/downloads).

Thanks!
Feel free to report back any other issues you find (I might not be always as active as right now).
Software development is a long cycle & maturity comes over time & I have 3 platforms to take care of. Android is still new!
