### ISSUE TITLE
Improvement of low number of candidates in search results

### ISSUE THREAD

**Issue by Denpun1** [harmonoid/harmonoid#337]

**Comment by alexmercerind** [comment]
Hi! I'd need a bit more clarification about this one.

**Comment by Denpun1** [comment]
Only up to 3 stream search results (song, video, album, community playlist, artist) will be displayed.

**Comment by alexmercerind** [comment]
Hi @Denpun1!

Thanks for the report, a similar issue is present at #275. I'd love to follow up there.

This may sound like a bummer, but this issue is very low priority for the project. For a number of reasons:
- Harmonoid is primarily a local music player & library manager.
- Integrating YouTube Music is a tedious process & isn't a primary feature.
- The result isn't very fruitful compared to the effort this would take.
  It means separately looking up every page's request, binding it in Dart & writing respective UI code.
  On the other hand, current search experience returns good-enough search results 99.9% of the times.
  One can change the query a bit to get the expected response or directly give a URL.
