### ISSUE TITLE
Ability to display the music by folder

### ISSUE THREAD

**Issue by samlach2222** [harmonoid/harmonoid#345]
Have the possibility to display the music by folder (as they are arranged in the file explorer).

This feature could take place in the horizontal bar where "Albums", "Tracks", "Artists" and "Playlist" are already located.

**Comment by alexmercerind** [comment]
Hi @samlach2222, sorry for replying late.
However, this feature is already present in the [Planned Features](https://github.com/harmonoid/harmonoid#planned-features) list on GitHub README.

Unfortunately, this & few other things are planned to be "Patreon only" because I need a way to thank those existing supporters to the project, hope you understand. Harmonoid itself is complete application & will receive features/fixes (it's still in development and needs fixes/features until I'm ready to call it a `1.0.0`), there will be no menus showing "Buy missing features" or any other annoying popups. It's just going to be an "even better" version for those who are/were close supporter of the project. I've spent plenty of time writing this application & various sub-modules used in it, it's been a journey.

Currently however, I'm kinda occupied with university & part-time.

Thanks!
