### ISSUE TITLE
Ability to play next song if played via Tracks tab

### ISSUE THREAD

**Issue by eedeidk** [harmonoid/harmonoid#353]
**Ability to play the songs consecutively instead of manually adding them via a queue**

The current system is good when played via Artist, Album etc tabs or the shuffle. 
But when user tries to play song via tracks tab, only that song is on the queue so the music just stops after its played. 
I think it would be better if you handle this in Rhythmbox's way, i.e. endless playing from any song.

I Hope you look into this. And many thanks for this great music player support on linux.

**Comment by alexmercerind** [comment]
Hi @eedeidk, thanks for the report.

Since this is already possible, I have marked this as a `question`.

**You can enable this from the settings.** This will load the next songs to the playlist, when played from TRACKS tab. See:

![](https://user-images.githubusercontent.com/28951144/202701206-b313833a-4a8c-4194-9f66-bec9325e006c.png)

This was default behaviour before last update (v0.3.4). However, some users have more over 70k songs, so adding all of them to playlist at once can degrade performance a lot.

<hr>

> I Hope you look into this. And many thanks for this great music player support on Linux.

Yeah! Linux is a focus point for me. There's a serious lack of good music players on Linux, Windows still has MusicBee.

I'm tired of long bland lists in Rythmbox etc. etc.

Harmonoid is all about being having a good/consistent vibrant UI/UX, providing users a way to manage/play their music in a more engaging way. In Harmonoid, album arts are displayed in most screens, most things auto-color based on the content etc. All of this, with rich animations wherever possible.
