### ISSUE TITLE
ALBUM PAGE - artist name is getting from "album artist" id3 tag only + some covers missing

### ISSUE THREAD

**Issue by wennaspeedy** [harmonoid/harmonoid#354]
1. I have some missing artists tags and I found out that you get artist name from tag "album artist". In my opinion this tag should be grabbed from "artist" tag in case of "album artist" is empty. Like other similar apps do.

2. I have also some missing album covers. I think that ".png" images are skipped. What image formats do you search for covers?

**Comment by alexmercerind** [comment]
Hi! May you please mail me the sample at <alexmercerind@gmail.com> or attach the file here for me to examine.

I do pull first artist from the `artist` tag if `album_artist` is missing. However, some corner case might be causing some fault.
Same for album art, all should work, mine do with FLAC, OGG, M4A/AAC or MP3 etc.

Thanks!

**Comment by alexmercerind** [comment]
Hi @wennaspeedy,

Looking at the situation once again. I think you're referring to non-embedded album arts (are you?).

They are also supported, only thing is that you need to enable them from the settings.

```dart
  'Folder.jpg',
  'Folder.png',
  'AlbumArtSmall.jpg',
  'AlbumArt.jpg',
  'Album.jpg',
  '.folder.png',
  'cover.jpg',
  'cover.png',
  'cover.gif',
  'front.jpg',
  'front.png',
  'front.gif',
  'front.bmp',
  'thumb.jpg',
```

![fallback_album_arts](https://user-images.githubusercontent.com/28951144/202733758-4bbc6238-962f-49bb-8329-07a026aff21a.jpg)

It's marked as "Experimental", however that's a concern for Android only.

**Comment by wennaspeedy** [comment]
I didn't see experimental features. Album covers work now!

**Comment by wennaspeedy** [comment]
But please don't find image files with case sensitive. Cover.jpg is not grabbed. 

I think the algorithm may be different. If you can't find cover by defined names, you may to try pick up the first image in folder.

**Comment by alexmercerind** [comment]
> But please don't find image files with case sensitive: "Cover.jpg" is not grabbed.
> I think the algorithm may be different. If you can't find cover by defined names, you may to try pick up the first image in folder.

This is intended. File system paths on Linux are case sensitive. Non-embedded album arts are not a standard (which Harmonoid caches locally after extracting from the file). I have taken above list of album arts from VLC's source:

https://code.videolan.org/videolan/vlc/-/blob/master/modules/meta_engine/folder.c#L40-55

Iterating over each folder just before rendering an album art will be quite expensive (will yield frame drops).
Some folders can be quite large (based on how people organize).
Infact, fallback album arts are as a whole somewhat expensive due to additional I/O calls to check for file existence.


<hr>

As for the album artist & artist issue, I can only proceed with a sample of the audio file causing the issue.

Thanks!
