### ISSUE TITLE
Contribute as a developer

### ISSUE THREAD

**Issue by 404-Chacal** [harmonoid/harmonoid#385]
I would like to contribute to this project

**Comment by alexmercerind** [comment]
Not possible presently likely.

It takes time to find good developers who write maintainable & stable code anyways. I can't afford valuable time of such developers, because Harmonoid can't offer anything in return. I just work on this when I'm free now.

All the progress which Harmonoid has recently received was a result of me relentlessly implementing features, fixing bugs & writing stable code. However, people do get tired unfortunately.
