### ISSUE TITLE
Crop cover art taken from Youtube Music

### ISSUE THREAD

**Issue by ken-der-guru** [harmonoid/harmonoid#386]
**Describe the new feature you'd like**
Currently when you stream music and the cover  art is from a Youtube video that was uploaded on a Topic channel, it gets cropped like this:
![image](https://user-images.githubusercontent.com/117478249/210759046-425aab6d-3d85-4fef-9aa6-3a0d18d82a40.png)

Thoug in the Notifications of Gnome it looks like this, because it scales the picture so it fits:
![image](https://user-images.githubusercontent.com/117478249/210759209-cc171204-a3ec-477b-aab6-d75e231c2889.png)

It would be nice if the colored bars at the right and left side of the picture get automaticaly removed
![maxresdefault](https://user-images.githubusercontent.com/117478249/210762622-8f3dfd5b-7225-4b73-973e-d9da672642c2.jpg)

This would lead to the notification looking better like this:

![example](https://user-images.githubusercontent.com/117478249/210763296-95b5fab5-60e7-4777-aa19-8f3d9d277359.png)

When obtaining the cover art this way: `https://img.youtube.com/vi/<insert-youtube-video-id-here>/mqdefault.jpg` 
(or with the same resoulution every time).

Then the dimensions are always the same:
![mqdefault](https://user-images.githubusercontent.com/117478249/210771233-352477d6-8af3-401c-9c67-9981f46696e3.jpg)

because of these standard dimensions it should be possible to reliable remove those bars at the side of the thumbnail

**Comment by alexmercerind** [comment]
Thanks for the report!

Yeah! My installation of elementaryOS's media controls also shrink the non-square album arts in same way. I actually [did experiment & implement cropping of album arts into a square](https://gist.github.com/alexmercerind/688b73fdfdc33e0bf1937604ded13afa) the other day, however this didn't make it's way to Harmonoid yet.

The [package:image](https://pub.dev/packages/image) offers a direct method [`copyResizeCropSquare`](https://github.com/brendan-duncan/image/blob/main/doc/transform.md#copyresizecropsquare) for it. Since, dealing with image editing seemed computationally expensive, I left it in hurry. I'll try to get this done before next stable release.

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
