### ISSUE TITLE
More customisation in now playing screen

### ISSUE THREAD

**Issue by florinsdistortedvision** [harmonoid/harmonoid#388]
Hello, great player, was thinking, instead of picking manually a background for Music Playback screen, have harmonoid take the album art and blur it (maybe dynamically moving it - similarly to how Tidal and Apple Music is doing). Additionally have options to center lyrics or customize it more (font, size, position, etc).
Example of what can it look like:

![image](https://user-images.githubusercontent.com/97384306/211061501-1b989839-4398-4755-9a87-e724dff2bd23.png)
![image](https://user-images.githubusercontent.com/97384306/211061563-d829c7d2-fbf0-4427-80a0-31b20faed582.png)

**Comment by alexmercerind** [comment]
Blur is not a standard part of Material Design (which Harmonoid consistently follows). However, I do understand the request.

- It is already possible to change the font size (both active & inactive lyric).

Font & position (?) is overkill. I don't think the two cited music services (with thousand of employed developers) allow it either. There are far more important & crucial feature requests which I'd like to get over the line first.

Thanks!

**Comment by florinsdistortedvision** [comment]
Well the cited sources might have thousand of employed devs indeed, but something very similar can be done with Foobar + plugin. 

![image](https://user-images.githubusercontent.com/97384306/211148884-bbe0121f-a478-4883-b4a5-5eccfbd4bb73.png)
![image](https://user-images.githubusercontent.com/97384306/211148898-75ac3d89-d9bf-4896-a141-bb44f5455e13.png)

**Comment by alexmercerind** [comment]
No plugin API is made yet. How does a plugin count as first party implementation from project dev?

**Comment by florinsdistortedvision** [comment]
Plugin comes with foobar. They call it plugins however.

**Comment by alexmercerind** [comment]
It's not first party in foobar2000 either. That's community made (which again increases the developer count). Similarly, it's not my responsibility to implement everything. I prioritise features & bugs based on their importance in project & my personal requirements. AND... I have actual life & responsibilities besides this.

Secondly, **you can't compare a 2 year old project with a 21 year old project**. It's an awful lot amount of time, which has gone into development of something like foobar2000. With that being said, because Harmonoid is so young, there are far more important things to implement already.

On the other hand, my priorities are about having a decent music experience which meets actual requirements while giving an engaging user interface with fluid animations wherever anything is drawn.

There are other things which foobar doesn't do (or atleast out of box) as compared to Harmonoid. And it's fine, use whatever you want.

<hr>

Changed issue title. Your suggestion is not _better_ (it's subjective). I like my Lo-Fi backgrounds better while listening to music.

**Comment by indeedwatson** [comment]
I'm really confused by the choice of including an image background feature that doesn't use the album art by default. It seems like the sane default choice. The pixel art images are neat, but to not even give the option to use the album art is very puzzling. Better or not, I think most people would want the music, the lyrics, and the art, to all belong to the thing you're listening to. To have one of these elements be completely arbitrary is rather strange.

I wouldn't want it blurred either, just darkened probably.

Anyway, even tho this comment might sound negative, I'm saying this because this is so far the only music player on linux that seems good to me, that's a big compliment, and this feature is the only thing that stands out as a negative so far.

**Comment by alexmercerind** [comment]
Thanks for appreciation. At the moment, you can also use the palette color from album art as background.
I believe it is more neutral (less opinionated/subjective) design choice as compared to pixel arts. Press arrows in bottom-right.
OR... Load your own image backgrounds from 'Settings'.
More options surely are possible. I lack time unfortunately.


![](https://user-images.githubusercontent.com/28951144/226111258-732bdfb3-f731-4e9b-b171-5675b710ae54.png)


I also had plans to add shader based backgrounds, e.g. ['Star Nest' @ shadertoy.com](https://www.shadertoy.com/view/XlfGRj).
Flutter recently added support for shaders. These are really performant & minimal.

Another idea (which never got over the line) is audio based visualizer, e.g. [an old video showing captured audio samples from Harmonoid which may be used for audio visualization](https://user-images.githubusercontent.com/28951144/226111215-6ce18963-e721-4295-9654-073e7071dfcb.mp4).

I built this project for myself, I like quality & stability. I have no haste. One goal is to meet requirements of current/previous project supporters & sponsors. I'm really thankful to them.

**Comment by alexmercerind** [comment]
> I wouldn't want it blurred either, just darkened probably.

A 480px x 480px album art will get pixelated on that large area. Not a good idea.

**Comment by indeedwatson** [comment]
Thanks, I wasn't aware of that option. Unfortunately yesterday I noticed a huge CPU consumption from this program so I'm probably going back to mpv as my music player.

**Comment by alexmercerind** [comment]
> Unfortunately yesterday I noticed a huge CPU consumption from this program.

Performance on GNU/Linux is retarded.
Same running on Windows with entry-level Ryzen 3 2200U Mobile:

Under 100 MB of RAM & < 5% CPU usage with "Now Playing Screen" visible. <1 % CPU in music library UI.

![](https://user-images.githubusercontent.com/28951144/208625337-9272ea1b-9b07-40f4-bdd6-32fa80b4068c.jpg)

**Comment by alexmercerind** [comment]
https://github.com/flutter/flutter/issues/88996
https://gitlab.gnome.org/GNOME/gtk/-/issues/4704

What a joke.
