### ISSUE TITLE
UI Scaling or Font Size control

### ISSUE THREAD

**Issue by aandrew-me** [harmonoid/harmonoid#392]
Firstly, thanks for making such a wonderful app.

The thing is that text in the app is a bit small on my Laptop screen (1920x1080). And this has been an issue with other flutter apps too. 

So if there is a way to increase the size of elements in app it would be very helpful. 
It maybe something like this -
![image](https://user-images.githubusercontent.com/66430340/212468039-55403ee6-fb1d-4263-a6f1-37249bf255c0.png)

Or maybe a setting to change font size.

**Comment by alexmercerind** [comment]
Hi! Thanks for the encouraging words.

To my best knowledge, there isn't really a viable & performant fractional scaling available for Linux on any desktop environment. Most "scaling" options just change the font scale (which is then inferred by GTK applications). Here X.org & Wayland have separate set of issues. Other options like `xrandr` hacks just cramp out the CPU/GPU.

On Windows, the scaling of UI elements & text is correct (both UI & text scale) e.g. 125%, 150% 175%.
On macOS, IIRC they don't even allow fractional scaling & operate on 200% etc. by default on high-DPI displays.

Since, Flutter is custom rendered using GL. **It is possible.** I did experiment with [`FractionallySizedBox`](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) the other day & I could get working fractional scaling (which was better than font scaling provided by host OS).

<hr>

That's screenshot from Telegram Desktop right?

_It's one of the applications I find really well-crafted. Good animations, UI, features & experience. I like this kind-of work._

**Comment by aandrew-me** [comment]
Hello!
You're right, fractional scaling is a mess.
But great to know that its possible with Flutter. 

And right, the screenshot is from Telegram Desktop. Its indeed a very nice app!
