### ISSUE TITLE
Respect .nomedia inside a folder in android, don't cache the folder if it is there

### ISSUE THREAD

**Issue by prateekmedia** [harmonoid/harmonoid#394]
**Describe the new feature you'd like**

Currently all folders music are getting cached, some people who have .nomedia file in that folder, even then it is grating cached. This is not an intended behavior in android, please fix it

**Comment by alexmercerind** [comment]
Don't add the folders which you don't want to index (available in Harmonoid's settings). Harmonoid is one of the very few music players on Android which actually allow to manually select the music folders.

`.nomedia` etc. is a part of Android's permission standard & not something developers implement anymore (speaking of Android 11+ i.e. scoped storage).

**Example:**

Chances are if you create a new `.nomedia` & restart your phone, Android's bullshit filesystem won't allow Harmonoid (or any other application) to play/read/view the files which just got affected by `.nomedia`.
What I mean is that, modern Android storage is very restrictive & `.nomedia` is something which is handled by it internally.

By current correct standards, any application which uses normal `MediaStore`/`java.io.File` APIs without `MANAGE_EXTERNAL_STORAGE` is not able to view/read/access those `.nomedia`d files (system behaves like they don't exist, only to the application).

But as you can tell, it doesn't work "correctly", BUT it will get refreshed upon restart. I can't tell if this is fixed in Android 13.

My best advice is to stay away from `.nomedia` & just add the folders where your music is. By default, Harmonoid adds whole local storage.

**Comment by prateekmedia** [comment]
So how about adding exceptions to folder?

**Comment by alexmercerind** [comment]
I don't find the need. It's same for all platforms Windows, Linux & macOS. Just don't add the folders where your music isn't.
