### ISSUE TITLE
Sync Imported Playlists

### ISSUE THREAD

**Issue by Nesaijn** [harmonoid/harmonoid#397]
There are already vague mentions of this and #228 seems to be the main solution for that but I would like to mention another more simple solution to that.

The idea is to save the URL the playlist was imported from at the beginning so that you are able to manually and/or automatically update the changes by fetching the data from that URL again.

**Comment by alexmercerind** [comment]
**Harmonoid is a local music player.**

I don't want to deal with any music service & any terms of conditions etc. Sharing just the URLs & playlists won't work for local files. If a playlist syncing API is ever made, we need to do file sharing (upload/download) too (to which URLs inside that playlist will point to). But, this is also redundant, because I much rather support existing syncing standards e.g. Jellyfin or Subsonic.

- #315
- #375

The feature would be really interesting though, a playlist can be created on the internet & synced personally between devices or shared between multiple friends. A really useful & enjoyable thing to have.

Thanks for the idea, I had similar vision about adding this before-hand. It will be really easy to implement in-fact. A single relational table or firebase document etc. for each playlist would work flawlessly, but still everything takes time in development, tests & roll-out. There's already a long list of requested features already & I've realised these requests will never stop, so I'm stopping. I want to live in peace for a while & work on my career instead of this.

There are no resources, time & funds to proceed with this on the other hand.

**Comment by alexmercerind** [comment]
The "List":

- #348
