### ISSUE TITLE
Add MPRIS support for linux

### ISSUE THREAD

**Issue by prateekmedia** [harmonoid/harmonoid#90]
**Describe the new feature you'd like**

On linux when playing any music no music control is visible on notification. It would be good if it shows one.

**Comment by prateekmedia** [comment]
@alexmercerind  I think this might be easy as harmonoid uses flutter_local_notifications(idk why) but it has got linux support https://pub.dev/packages/flutter_local_notifications/versions/9.0.0-dev.4/changelog.

**Comment by alexmercerind** [comment]
I'm more experienced about Windows & I don't know much about Linux (I just write for it because it also uses C++ for the most part).

But, maybe [dart-mpris](https://github.com/jld3103/dart-mpris) is likely what we need. Or maybe, I can build the same in `libwinmedia` itself because Windows already shows system media transport controls. I'm currently not sure.

**Comment by prateekmedia** [comment]
@alexmercerind Is this being worked on? Cause this is the only thing that stops harmonoid from being my default player on linux.

**Comment by alexmercerind** [comment]
![](https://github.com/harmonoid/harmonoid/raw/assets/linux_full/4.jpeg?raw=true)

Release: https://github.com/harmonoid/harmonoid/releases/tag/v0.2.0
